#!/bin/sh
DOCKER_OPTS=""
while getopt --long insecure,insecure-registry: -- "$@"; do
  case $opt in
    --insecure)
      DOCKER_OPTS="${DOCKER_OPTS} --insecure-registry='0.0.0.0/8'"
      ;;
    --insecure-registry)
      DOCKER_OPTS="${DOCKER_OPTS} --insecure-registry='${2}'"
      shift
      ;;
  esac
done

docker -d -b none -s vfs $DOKCER_OPTS 2>/dev/null >/dev/null & sleep 1
docker pull $1 2>/dev/null >/dev/null &&
docker save $1
